import type { MarketplaceSnapshot } from "@/types/marketplace";

export const initialMarketplace: MarketplaceSnapshot = {
  wallet: {
    balance: 2450,
    pendingPayment: 320,
    bidLimit: 10000,
  },
  activities: [
    { id: "act-1", title: "กันวงเงิน", detail: "Pikachu ex (SAR) ฿12,750" },
    { id: "act-2", title: "เติมเงิน", detail: "QR PromptPay ฿2,000" },
    { id: "act-3", title: "ขายสำเร็จ", detail: "Blue-Eyes White Dragon ฿22,500" },
  ],
  products: [
    {
      id: "pika-sar",
      title: "Pikachu ex (SAR)",
      code: "SV8 132/106",
      seller: "BidMaster99",
      topBidder: "BidMaster99",
      mode: "auction",
      category: "pokemon",
      rarity: "SAR",
      openingPrice: 1000,
      currentPrice: 12750,
      nextBid: 13000,
      watchers: 124,
      endsIn: "00:03:28",
      imagePositionClass: "object-pos-1",
      hot: false,
    },
    {
      id: "charizard-sar",
      title: "Charizard ex (SAR)",
      code: "SV3 134/108",
      seller: "DragonSlayer",
      topBidder: "DragonSlayer",
      mode: "auction",
      category: "pokemon",
      rarity: "SAR",
      openingPrice: 2500,
      currentPrice: 18600,
      nextBid: 19000,
      watchers: 98,
      endsIn: "00:07:54",
      imagePositionClass: "object-pos-2",
      hot: false,
    },
    {
      id: "luffy-sec",
      title: "มังกี้ ดี. ลูฟี่",
      code: "OP05-119 SEC",
      seller: "StrawHat",
      topBidder: "StrawHat",
      mode: "auction",
      category: "onepiece",
      rarity: "SEC",
      openingPrice: 1500,
      currentPrice: 7200,
      nextBid: 7500,
      watchers: 76,
      endsIn: "00:12:11",
      imagePositionClass: "object-pos-3",
      hot: false,
    },
    {
      id: "blue-eyes",
      title: "Blue-Eyes White Dragon",
      code: "QCAC-JP021 (25th)",
      seller: "KaibaCorp",
      topBidder: "KaibaCorp",
      mode: "auction",
      category: "single",
      rarity: "UR",
      openingPrice: 3000,
      currentPrice: 22500,
      nextBid: 23000,
      watchers: 67,
      endsIn: "00:18:45",
      imagePositionClass: "object-pos-4",
      hot: false,
    },
    {
      id: "giratina-sa",
      title: "Giratina V (SA)",
      code: "S11 111/100",
      seller: "MintLab",
      topBidder: "MintLab",
      mode: "auction",
      category: "pokemon",
      rarity: "SR",
      openingPrice: 2500,
      currentPrice: 9450,
      nextBid: 9800,
      watchers: 58,
      endsIn: "00:22:31",
      imagePositionClass: "object-pos-5",
      hot: true,
    },
    {
      id: "lugia-sa",
      title: "Lugia V (SA)",
      code: "S12 110/098",
      seller: "SilverWing",
      topBidder: "SilverWing",
      mode: "auction",
      category: "pokemon",
      rarity: "SR",
      openingPrice: 2200,
      currentPrice: 8900,
      nextBid: 9200,
      watchers: 46,
      endsIn: "00:25:47",
      imagePositionClass: "object-pos-6",
      hot: true,
    },
    {
      id: "nami-sp",
      title: "Nami (SP)",
      code: "OP01-016",
      seller: "GrandLine",
      topBidder: "GrandLine",
      mode: "auction",
      category: "onepiece",
      rarity: "SP",
      openingPrice: 2000,
      currentPrice: 6300,
      nextBid: 6600,
      watchers: 39,
      endsIn: "00:28:09",
      imagePositionClass: "object-pos-1",
      hot: true,
    },
    {
      id: "obito-sp",
      title: "Obito Uchiha (SP)",
      code: "NRP-021",
      seller: "ShinobiCards",
      topBidder: "ShinobiCards",
      mode: "auction",
      category: "single",
      rarity: "SP",
      openingPrice: 1800,
      currentPrice: 5800,
      nextBid: 6100,
      watchers: 33,
      endsIn: "00:30:12",
      imagePositionClass: "object-pos-2",
      hot: true,
    },
    {
      id: "gengar-hr",
      title: "Gengar VMAX (HR)",
      code: "S10a 020/071",
      seller: "GhostRare",
      topBidder: "GhostRare",
      mode: "auction",
      category: "pokemon",
      rarity: "HR",
      openingPrice: 4500,
      currentPrice: 10250,
      nextBid: 10600,
      watchers: 29,
      endsIn: "00:33:55",
      imagePositionClass: "object-pos-3",
      hot: true,
    },
  ],
};

